### ISSUE TITLE
Unity versions from Unity Hub marked as manually installed

### ISSUE THREAD

**Issue by i0ntempest** [vrc-get/vrc-get#1071]
### Description of the bug / バグの説明

It looks like the list for nstalled Unity versions does not seem to update unless Settings pane is opened, and sometimes it detects hub-installed ones as manually installed.

### Steps to Reproduce / 再現手順

1. Install a new version of Unity while ALCOM isn't running
2. Open ALCOM and checkout the settings page. The new installation isn't there.
3. Relaunch ALCOM and check again. Now the new installation should be there but it could be marked as manully installed.
4. Relaunch again, now everything is correct.

### Expected Behavior / 想定される挙動

ALCOM should refresh (and correctly) this list on launch.

### Software Version / バージョン情報

0.1.7

### OS

macOS 14.5

**Comment by anatawa12** [comment]
It looks it's compound problem.

> It looks like the list for installed Unity versions does not seem to update unless Settings pane is opened

ALCOM loads Unity from Unity Hub but it takes several seconds. Could you confirm you have wait for several seconds (and move open projects page) after few seconds?

I think "2. Open ALCOM and checkout the settings page. The new installation isn't there." is because unity hub took several seconds to return ALCOM list of Unity Hub so if you opened settings page just after opening ALCOM, it will not load unity from unity hub.

It looks "3. Relaunch ALCOM and check again. Now the new installation should be there but it could be marked as manully installed." is because of ALCOM forgets to mark unity as from unity hub on adding unity. Thank you for reporting.

**Comment by i0ntempest** [comment]
Indeed, if I wait some time then the list is updated, but yea it is still marked as manual.
