### ISSUE TITLE
com.vrchat.core.vpm-resolver not installed by default

### ISSUE THREAD

**Issue by JustBuddy** [vrc-get/vrc-get#1180]
### Summary / 概要

Relates to this issue: https://github.com/JustBuddy/unitypackage-icon-tool/issues/3
As I found out, `com.vrchat.core.vpm-resolver` contains the data for the library `ICSharpCode.SharpZipLib`, not the base SDK.
However, the only way to check for SDK presence for .dll extensions is the defined constraint "`!VRC_SDK_VRCSDK3`", there is no feasible way to make this more granular.

We can also not add `com.vrchat.core.vpm-resolver` as dependency, as it is supposed to be able to run without VRCSDK as well, it is just SDK-aware.

ALCOM (or vrc-get) deviates from VCC by not installing `com.vrchat.core.vpm-resolver` (or replacement) into new projects.

This breaks tools that depend on `ICSharpCode.SharpZipLib`, but are also VRCSDK-aware.

### Request

Add `com.vrchat.core.vpm-resolver` into ALCOM/vrc-get template projects, ability for users to uninstall it can be kept as is.

### Additional context / 補足

\Packages\com.vrchat.core.vpm-resolver\Editor\Dependencies\ICSharpCode.SharpZipLib.dll

VCC forces the package to be installed.

![image](https://github.com/vrc-get/vrc-get/assets/8122264/4c72e244-c51e-4556-9150-71c168ce378c)

**Comment by anatawa12** [comment]
Relates to #1090 

Not installing resolver is by design and I don't want to change.

In my personal opinion, any upm package should not bundle any (real) nuget dll and should only bundle renamed dll if needed as Unity.Burst.Unsafe.dll, which is System.Runtime.CompilerServices.Unsafe, inside com.unity.burst package does, to avoid dll name conflict.

**Comment by JustBuddy** [comment]
That seems to work on our end, I will cross-check with my tool dev.

**Comment by anatawa12** [comment]
Please note that I think it may not work well with just renaming dll file; we shoud update assembly name in the dll file. (it looks work as expected in many case but if there are multiple version of same library, (like one dll is older tan the other) It may cause problems like method not found I think.)

**Comment by JustBuddy** [comment]
Thank you for the imformations.

We will handle this on our end.

**Comment by Sayamame-beans** [comment]
vpm-resolverに関する依存があるパッケージが、(必要な部分を依存関係にする等ではなく)vpm-resolver自体を依存関係に指定しているのを見かけました。(もしかすると、実際にvpm-resolver本体の何らかの挙動に依存するのかもしれませんが)

vpm-resolverの挙動による問題でテンプレートに含めるのを避けている場合、vrc-get-resolverで互換性を保ちつつ問題を解決することは(理論上)可能でしょうか?
互換性を保ちつつ問題を避けることが出来れば、vrc-get-resolverでvpm-resolverをlegacyPackageとして指定することが出来そうです。

**Comment by JustBuddy** [comment]
@Sayamame-beans the main issue is that my asset in question does not rely on VRChat SDK or any other parts of it, it is a unity tool distributed the same way. Meaning, we can not depend on vpm-resolver itself.
The asset is VRChat-aware, so if VRCSDK is present it uses its SharpZipLib, if not it uses our own. However, due to ALCOM not installing vpm-resolver by default, we can no longer rely on that Editor flag to check for SDK presence.

**Comment by Sayamame-beans** [comment]
@JustBuddy OK, I understand your case.

I personally feel vpm-depending on vpm-resolver itself is undesirable a bit, or implicit depending on dependants of vpm-resolver is not good, but this seems also causing vizvid breaking, etc. (investigating https://twitter.com/JLChnToZ/status/1836340582676893719)

I'd like to find a compromise.

**Comment by Sayamame-beans** [comment]
:thinking: 
- Vizvid
> It rely on the VPM resolver API to query updates.
https://twitter.com/JLChnToZ/status/1836586167443296586

(Does vpm-resolver have Public API?)
- ArchiTech.VideoPlayerShim
> I've observed it uses the bundled schematic version parser and comparer in VPM resolver.
https://twitter.com/JLChnToZ/status/1836587137409667311

**Comment by anatawa12** [comment]
> (Does vpm-resolver have Public API?)

I feel no. visvid just invokes internal things that are exposed as public but those are not guaranteed to work in the future.

(Note: vpm-resolver is not 1.x so according to semantic versioning there is no stable API.

I think it's almost impossible to provide API similar to vpm resolver since vrc-get-resolver is just a wrapper of vrc-get and no detailed access to vpm client.

**Comment by JLChnToZ** [comment]
VizVid dev here

According to [VPM documentation](​https://vcc.docs.vrchat.com/vpm/resolver/#getting-it), this component should not be removed from the projects and that's why its remove button in VCC is disabled.

Therefore I (and some other asset/tool developers) assume public classes and methods inside this package are considered available by official VRCSDK.

I agree that this is quirky as nothing is "explicitly" depending on it.

So I still thinks your decision makes projects created by your tool is non-standard and not 100% compatible to official tools created ones.

Anyways I added a workaround to my video player to make it works with your tool few versions ago.

**Comment by anatawa12** [comment]
one of official vpm client like VPM CLI can remove the VPM Resolver so I think it's not fatal to remove vpm resolver with vpm projects. VCC also detects as vpm project.

non standard is yes. but I think I believe not having resolver is better for several reasons so I implemented in this way. (e.g. with unity 2022, resolver is much less useful because of safe mode and resolver is (was?) buggy with in-developing packages)

I think resolver doesn't have public API (there are publicly leaked things are there though) so I think it's not good to use public things on resolver. (resolver is still 0.x)

> Anyways I added a workaround to my video player to make it works with your tool few versions ago.

Thank you.
