### ISSUE TITLE
ALCOM forces Debug mode to be enabled by default on projects opened through ALCOM

### ISSUE THREAD

**Issue by sacred0** [vrc-get/vrc-get#1250]
### Description of the bug / バグの説明

When opening any project via ALCOM, it enables Debug mode which makes scripts run slower and disables Burst optimizations. This is not the case when opening projects using VCC, Unity hub, or opening a scene file directly. The issue appears to be caused by the "-debugCodeOptimization" launch option being added by default to all projects. 

### Steps to Reproduce / 再現手順

1. Ensure Debug mode mode is disabled (Mode: Release) in the bottom right of the Unity window
![image](https://github.com/vrc-get/vrc-get/assets/105738663/99f4c179-acee-4db4-abed-dcea682036e6)
2. Open project via ALCOM. Debug mode should get enabled

### Expected Behavior / 想定される挙動

Debug mode should not be enabled automatically, to match the behavior of VCC and Unity hub.

### Screenshots / スクリーンショット

![image](https://github.com/vrc-get/vrc-get/assets/105738663/1fa0cdb3-d37a-4eee-906e-0bf446e9cebf)

### Software Version / バージョン情報

v0.1.9

### OS

Windows 10 Home 22H2

**Comment by orels1** [comment]
Would love to know what lead to this being a default option 👀

**Comment by anatawa12** [comment]
That's intended and short reason is to enable mono debugger protocol. if mono debugger protocol can be enabled without debugCodeOptimization, I'll use that.

ALCOM is planned to include some tool to collect&share console log to ask friends about happening error. (#297)
The tool (currently) depending on mono debug protocol and it won't be enabled unless we enabled debugCodeOptimization.
However, if there are compilation errors, we cannot enable debugger. it's not good since compilation errors are most asking error type.

In addition, other tools like Rider adds it by default without any notice and I believe it won't make code slow much. (Unity 2019 or older have debug enabled by default AFAIK)

**Comment by orels1** [comment]
There are definitely performance benefits from running in release mode, which is partially why 2022 is faster than 2019. Something like rider or VSCode makes Unity show a large "Debugger Attach Request" pop-up appear when first connecting explaining what is about to happen.

I feel like it would be nice if there was an option in ALCOM to not enable this for every project by default - for more advanced users who do not need the log extraction 👀

**Comment by anatawa12** [comment]
> I feel like it would be nice if there was an option in ALCOM to not enable this for every project by default - for more advanced users who do not need the log extraction 👀

Yes. I'm planned to implement such flag or customizing command line arguments for all projects.

> Also, is there something special in the log you get from the mono debugger log versus just reading Editor.log?

Editor.log can be overridden easily by launching multiple unity (by mistake or intentionally) so I choose mono debug protocol.
Also, editor.log has too detailed information, which make harder to read. In most cases, console info is enough for investigation.

**Comment by orels1** [comment]
I see, thank you for the information!

**Comment by anatawa12** [comment]
News for this issue. The tool I made no longer requires debugCodeOptimization so I'm going to remove -debugCodeOptimization by default since next release. 

Please see #1716 for more details
