### ISSUE TITLE
Simplified Chinese font weight is not obvious

### ISSUE THREAD

**Issue by lonelyicer** [vrc-get/vrc-get#1410]
**Example:**
English:
![image](https://github.com/user-attachments/assets/3ad3cd48-4648-4386-b0ba-9e43e0278f23)
Simplified Chinese:
![image](https://github.com/user-attachments/assets/9b1d5db3-c2e2-4a73-9d06-1e3078798d4b)

**Comment by anatawa12** [comment]
Their heading font weight is normal (400) and same as other texts like system information list below.

Due to font scaling and rendering algorithm, heading text looks a little bold but it's not a important I think.

Because CJK ideograph characters has more complicated than alphabets, their font has thinner lines in most case (and your case) so It's a harder to experience line width difference came from font size different than alphabet characters, I think.

**Comment by lonelyicer** [comment]
> Their heading font weight is normal (400) and same as other texts like system information list below.
But this may cause the interface to look more cluttered with CJK fonts, I think.
Especially if there is no obvious dividing line between the content and the title.

**Comment by anatawa12** [comment]
Oh I found I forget to add spacing between section title and body.

<img width="460" alt="image" src="https://github.com/user-attachments/assets/5f1d60e8-0f21-4196-839e-e087ef1a7f92">

how do you think this?

**Comment by lonelyicer** [comment]
It looks better.
